// tabbar
export const HOME_SCREEN = 'HOME_SCREEN';
export const RESTAURANTS_SCREEN = 'RESTAURANTS_SCREEN';
export const SEARCH_SCREEN = 'SEARCH_SCREEN';
export const PROFILE_SCREEN = 'PROFILE_SCREEN';

export const SPLASH_SCREEN = 'SPLASH_SCREEN'; // Screen Splash
export const MAIN_SCREEN = 'MAIN_SCREEN';
export const CART_SCREEN = 'CART_SCREEN';
export const CHECKOUT_SCREEN = 'CHECKOUT_SCREEN';
export const CART_FINAL_SCREEN = 'CART_FINAL_SCREEN';
export const THANK_YOU_SCREEN = 'THANK_YOU_SCREEN';
export const ORDER_STATUS_SCREEN = 'ORDER_STATUS_SCREEN';
export const ADD_TO_BASKET_SCREEN = 'ADD_TO_BASKET_SCREEN';
export const RESTAURANT_DETAIL_SCREEN = 'RESTAURANT_DETAIL_SCREEN';
export const FOOD_DETAIL_SCREEN = 'FOOD_DETAIL_SCREEN';
